theme: minima
title: Richard's Technical Paraphernalia 
author: Richard Davies
description: Aide-m√©moire for the ageing developer
layout: default
url: "https://blog.richy.net/"
plugins:
  - jekyll-sitemap

